INSERT INTO COUNTRY (COUNTRY_NAME, COUNTRY_CODE, MAX_MOBILE_LENGTH)
 VALUES
 ('Australia','+61', 9),
 ('Canada','+1', 10),
 ('India','+91', 10),
 ('Singapore','+65', 8),
 ('United Kingdom','+44', 10),
 ('United States','+1', 10);

INSERT INTO MASTER_DATA (TYPE, VALUE)
VALUES
 ( 'Function','BPO'),
 ( 'Function','Human Resources (HR)'),
 ( 'Function','Information Technology (IT)'),
 ( 'Function','Manufacturing'),
 ( 'Function','Office Administration'),
 ( 'Function','Sales'),

 ( 'Education','BA'),
 ( 'Education','BAMS'),
 ( 'Education','BArch'),
 ( 'Education','BBA'),
 ( 'Education','BBM'),
 ( 'Education','BBS'),
 ( 'Education','BCA'),
 ( 'Education','BCCA'),
 ( 'Education','BCM'),
 ( 'Education','BCom'),
 ( 'Education','BCS'),
 ( 'Education','BDes'),
 ( 'Education','BDS'),
 ( 'Education','BE'),
 ( 'Education','BEd'),
 ( 'Education','BFA'),
 ( 'Education','BFT'),
 ( 'Education','BHM'),
 ( 'Education','BHMS'),
 ( 'Education','BIT'),
 ( 'Education','BMM'),
 ( 'Education','BMS'),
 ( 'Education','BPharma'),
 ( 'Education','BSc'),
 ( 'Education','BSSE'),
 ( 'Education','BTech'),
 ( 'Education','BVSc'),
 ( 'Education','Commercial Art'),
 ( 'Education','Diploma'),
 ( 'Education','Diploma in Graphics & Animation'),
 ( 'Education','Fashion/Designing'),
 ( 'Education','GDBA'),
 ( 'Education','HSC'),
 ( 'Education','LLB'),
 ( 'Education','MBBS'),
 ( 'Education','Vocational Training'),
 ( 'Education','ACCA'),
 ( 'Education','CA'),
 ( 'Education','CA IPCC'),
 ( 'Education','CFA'),
 ( 'Education','CS'),
 ( 'Education','CWA'),
 ( 'Education','EMBA'),
 ( 'Education','FCA'),
 ( 'Education','I PG Course'),
 ( 'Education','ICAI/CMA'),
 ( 'Education','ICWA'),
 ( 'Education','Journalism/Mass Comm'),
 ( 'Education','LLM'),
 ( 'Education','MA'),
 ( 'Education','MArch'),
 ( 'Education','MBA'),
 ( 'Education','MBA/PGDM'),
 ( 'Education','MBM'),
 ( 'Education','MCA'),
 ( 'Education','MCM'),
 ( 'Education','MCom'),
 ( 'Education','MDBA'),
 ( 'Education','MDP'),
 ( 'Education','ME'),
 ( 'Education','MEd'),
 ( 'Education','MEP'),
 ( 'Education','MFA'),
 ( 'Education','MFC'),
 ( 'Education','MFM'),
 ( 'Education','MMS'),
 ( 'Education','MPharma'),
 ( 'Education','MPhil'),
 ( 'Education','MPM'),
 ( 'Education','MS'),
 ( 'Education','MS CS'),
 ( 'Education','MS in Industrial Psychology'),
 ( 'Education','MS/MD'),
 ( 'Education','MSc'),
 ( 'Education','MSW'),
 ( 'Education','MTech'),
 ( 'Education','MVSc'),
 ( 'Education','Other'),
 ( 'Education','PG Diploma'),
 ( 'Education','PGCBM'),
 ( 'Education','PGCHRM'),
 ( 'Education','PGDAC'),
 ( 'Education','PGDBA'),
 ( 'Education','PGDCA'),
 ( 'Education','PGM'),
 ( 'Education','PGP'),
 ( 'Education','PGPBM'), 
 ( 'Education','PHD'),
 ( 'Education','PR/Advertising'),
 ( 'Education','Tourism'),

 ( 'Question Type','Multiple choice'),
 ( 'Question Type','Radio button'),
 ( 'Question Type','User enterable'),

 ( 'Address Type','Job Location'),
 ( 'Address Type','Interview Location'),
 ( 'Address Type','Both'),

 ( 'Importance Level','Low'),
 ( 'Importance Level','Mid'),
 ( 'Importance Level','High'),

 ( 'Stage','Source'),
 ( 'Stage','Screen'),
 ( 'Stage','Interview'),
 ( 'Stage','Offer'),

 ( 'Process','Hiring Manager'),
 ( 'Process','Lead Recruiter'),
 ( 'Process','Sourcing'),
 ( 'Process','Screening'),
 ( 'Process','Interview'),
 ( 'Process','Offer Management'),

 ( 'Expertise','Beginner'),
 ( 'Expertise','Competent'),
 ( 'Expertise','Expert'),

 ( 'Experience Range', '0 - 3 yrs'),
 ( 'Experience Range', '4 - 7 yrs'),
 ( 'Experience Range', '8 - 12 yrs'),
 ( 'Experience Range', '13 - 15 yrs'),
 ( 'Experience Range', '17 - 20 yrs'),
 ( 'Experience Range', '20+ yrs');