INSERT INTO COUNTRY (COUNTRY_NAME, COUNTRY_CODE, MAX_MOBILE_LENGTH)
 VALUES
 ('Australia','+61', 9),
 ('Canada','+1', 10),
 ('India','+91', 10),
 ('Singapore','+65', 8),
 ('United Kingdom','+44', 10),
 ('United States','+1', 10);

INSERT INTO MASTER_DATA (TYPE, VALUE)
VALUES
 ( 'function','BPO'),
 ( 'function','Human Resources (HR)'),
 ( 'function','Information Technology (IT)'),
 ( 'function','Manufacturing'),
 ( 'function','Office Administration'),
 ( 'function','Sales'),

 ( 'education','BA'),
 ( 'education','BAMS'),
 ( 'education','BArch'),
 ( 'education','BBA'),
 ( 'education','BBM'),
 ( 'education','BBS'),
 ( 'education','BCA'),
 ( 'education','BCCA'),
 ( 'education','BCM'),
 ( 'education','BCom'),
 ( 'education','BCS'),
 ( 'education','BDes'),
 ( 'education','BDS'),
 ( 'education','BE'),
 ( 'education','BEd'),
 ( 'education','BFA'),
 ( 'education','BFT'),
 ( 'education','BHM'),
 ( 'education','BHMS'),
 ( 'education','BIT'),
 ( 'education','BMM'),
 ( 'education','BMS'),
 ( 'education','BPharma'),
 ( 'education','BSc'),
 ( 'education','BSSE'),
 ( 'education','BTech'),
 ( 'education','BVSc'),
 ( 'education','Commercial Art'),
 ( 'education','Diploma'),
 ( 'education','Diploma in Graphics & Animation'),
 ( 'education','Fashion/Designing'),
 ( 'education','GDBA'),
 ( 'education','HSC'),
 ( 'education','LLB'),
 ( 'education','MBBS'),
 ( 'education','Vocational Training'),
 ( 'education','ACCA'),
 ( 'education','CA'),
 ( 'education','CA IPCC'),
 ( 'education','CFA'),
 ( 'education','CS'),
 ( 'education','CWA'),
 ( 'education','EMBA'),
 ( 'education','FCA'),
 ( 'education','I PG Course'),
 ( 'education','ICAI/CMA'),
 ( 'education','ICWA'),
 ( 'education','Journalism/Mass Comm'),
 ( 'education','LLM'),
 ( 'education','MA'),
 ( 'education','MArch'),
 ( 'education','MBA'),
 ( 'education','MBA/PGDM'),
 ( 'education','MBM'),
 ( 'education','MCA'),
 ( 'education','MCM'),
 ( 'education','MCom'),
 ( 'education','MDBA'),
 ( 'education','MDP'),
 ( 'education','ME'),
 ( 'education','MEd'),
 ( 'education','MEP'),
 ( 'education','MFA'),
 ( 'education','MFC'),
 ( 'education','MFM'),
 ( 'education','MMS'),
 ( 'education','MPharma'),
 ( 'education','MPhil'),
 ( 'education','MPM'),
 ( 'education','MS'),
 ( 'education','MS CS'),
 ( 'education','MS in Industrial Psychology'),
 ( 'education','MS/MD'),
 ( 'education','MSc'),
 ( 'education','MSW'),
 ( 'education','MTech'),
 ( 'education','MVSc'),
 ( 'education','Other'),
 ( 'education','PG Diploma'),
 ( 'education','PGCBM'),
 ( 'education','PGCHRM'),
 ( 'education','PGDAC'),
 ( 'education','PGDBA'),
 ( 'education','PGDCA'),
 ( 'education','PGM'),
 ( 'education','PGP'),
 ( 'education','PGPBM'), 
 ( 'education','PHD'),
 ( 'education','PR/Advertising'),
 ( 'education','Tourism'),

 ( 'questionType','Checkbox'),
 ( 'questionType','Radio button'),
 ( 'questionType','InputBox'),

 ( 'addressType','Job Location'),
 ( 'addressType','Interview Location'),
 ( 'addressType','Both'),

 ( 'importanceLevel','Low'),
 ( 'importanceLevel','Mid'),
 ( 'importanceLevel','High'),

 ( 'stage','Source'),
 ( 'stage','Screen'),
 ( 'stage','Interview'),
 ( 'stage','Offer'),

 ( 'process','Hiring Manager'),
 ( 'process','Lead Recruiter'),
 ( 'process','Sourcing'),
 ( 'process','Screening'),
 ( 'process','Interview'),
 ( 'process','Offer Management'),

 ( 'expertise','Beginner'),
 ( 'expertise','Competent'),
 ( 'expertise','Expert'),

 ( 'experienceRange', '0 - 3 yrs'),
 ( 'experienceRange', '4 - 7 yrs'),
 ( 'experienceRange', '8 - 12 yrs'),
 ( 'experienceRange', '13 - 15 yrs'),
 ( 'experienceRange', '17 - 20 yrs'),
 ( 'experienceRange', '20+ yrs');